//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement_396.Models.Contex
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SchoolMgmtEntities : DbContext
    {
        public SchoolMgmtEntities()
            : base("name=SchoolMgmtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<credential> credential { get; set; }
        public virtual DbSet<States> States { get; set; }
        public virtual DbSet<subject> subject { get; set; }
        public virtual DbSet<teacher> teacher { get; set; }
        public virtual DbSet<Student> Student { get; set; }
    
        public virtual ObjectResult<Sp_GetTeacherDetails_Result> Sp_GetTeacherDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetTeacherDetails_Result>("Sp_GetTeacherDetails");
        }
    
        public virtual ObjectResult<SP_GetStudentDetails_Result> SP_GetStudentDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetStudentDetails_Result>("SP_GetStudentDetails");
        }
    }
}
